"""Computational plasma physics: single-particle motion, MHD, waves, and kinetic theory.

Typical usage::

    import physicskit as pk
    import numpy as np

    # Cyclotron gyration of a proton in a 1 T field:
    r_hist, v_hist = pk.plasma.boris_integrate(
        np.zeros(3), np.array([1e5, 0.0, 0.0]),
        pk.plasma.QE, pk.plasma.MP,
        np.zeros(3), np.array([0.0, 0.0, 1.0]),
        dt=1e-10, steps=1000,
    )
"""

from .acceleration import simulate_wakefield_acceleration, wakefield_e_field
from .instabilities import (
    reconnection_field_from_flux,
    reconnection_harris_ic,
    reconnection_inflow_velocity,
    simulate_reconnection,
    simulate_weibel_filamentation,
    weibel_fastest_growing_mode,
    weibel_growth_rate,
)
from .kinetic import (
    deposit_number_density,
    interpolate_field,
    landau_damping_ic,
    landau_damping_rate,
    langmuir_wave_ic,
    maxwellian_velocities,
    pic_simulate,
    pic_step,
    solve_poisson_1d,
    two_stream_ic,
)
from .mhd import (
    MU0,
    alfven_speed,
    grad_shafranov_rhs_solovev,
    lundquist_number,
    magnetosonic_speeds,
    petschek_rate,
    resistive_diffusion_time,
    safety_factor_large_aspect_ratio,
    solovev_particular_solution,
    solve_grad_shafranov,
    sound_speed,
    sweet_parker_layer_width,
    sweet_parker_rate,
)
from .single_particle import (
    ME,
    MP,
    QE,
    boris_integrate,
    boris_push,
    curvature_drift,
    cyclotron_frequency,
    exb_drift,
    grad_b_drift,
    larmor_radius,
    magnetic_mirror_bounce,
    magnetic_moment,
    mirror_force,
)
from .turbulence import drift_wave_noise_ic, hasegawa_mima_rhs, simulate_hasegawa_mima
from .visualizers import (
    animate_alfven_wave,
    animate_drift_wave_turbulence,
    animate_ion_acoustic_soliton,
    animate_langmuir_wave,
    animate_reconnection,
    animate_two_stream_phase_space,
    animate_wakefield_acceleration,
    animate_weibel_filamentation,
    plot_cma_diagram,
    plot_drift_trajectory,
    plot_field_energy_history,
    plot_flux_surfaces,
    plot_particle_orbit_3d,
    plot_phase_space,
    plot_phase_space_interactive,
    plot_q_profile,
)
from .waves import (
    alfven_wave_pulse_ic,
    cma_coordinates,
    cold_plasma_dispersion,
    ion_acoustic_soliton_evolve,
    ion_acoustic_soliton_profile,
    plasma_frequency,
    rl_parameters,
    simulate_alfven_wave,
    stix_parameters,
    whistler_dispersion,
)

__all__ = [
    "QE",
    "ME",
    "MP",
    "MU0",
    "cyclotron_frequency",
    "larmor_radius",
    "magnetic_moment",
    "boris_push",
    "boris_integrate",
    "exb_drift",
    "grad_b_drift",
    "curvature_drift",
    "mirror_force",
    "magnetic_mirror_bounce",
    "alfven_speed",
    "sound_speed",
    "magnetosonic_speeds",
    "solovev_particular_solution",
    "grad_shafranov_rhs_solovev",
    "solve_grad_shafranov",
    "safety_factor_large_aspect_ratio",
    "lundquist_number",
    "resistive_diffusion_time",
    "sweet_parker_rate",
    "sweet_parker_layer_width",
    "petschek_rate",
    "plasma_frequency",
    "stix_parameters",
    "rl_parameters",
    "cold_plasma_dispersion",
    "whistler_dispersion",
    "cma_coordinates",
    "maxwellian_velocities",
    "landau_damping_ic",
    "langmuir_wave_ic",
    "two_stream_ic",
    "deposit_number_density",
    "interpolate_field",
    "solve_poisson_1d",
    "pic_step",
    "pic_simulate",
    "landau_damping_rate",
    "reconnection_harris_ic",
    "reconnection_inflow_velocity",
    "reconnection_field_from_flux",
    "simulate_reconnection",
    "weibel_growth_rate",
    "weibel_fastest_growing_mode",
    "simulate_weibel_filamentation",
    "ion_acoustic_soliton_profile",
    "ion_acoustic_soliton_evolve",
    "alfven_wave_pulse_ic",
    "simulate_alfven_wave",
    "drift_wave_noise_ic",
    "hasegawa_mima_rhs",
    "simulate_hasegawa_mima",
    "wakefield_e_field",
    "simulate_wakefield_acceleration",
    "plot_particle_orbit_3d",
    "plot_drift_trajectory",
    "plot_flux_surfaces",
    "plot_q_profile",
    "plot_phase_space",
    "plot_field_energy_history",
    "plot_cma_diagram",
    "plot_phase_space_interactive",
    "animate_reconnection",
    "animate_weibel_filamentation",
    "animate_two_stream_phase_space",
    "animate_langmuir_wave",
    "animate_ion_acoustic_soliton",
    "animate_drift_wave_turbulence",
    "animate_alfven_wave",
    "animate_wakefield_acceleration",
]
